# Generated by Django 5.1.4 on 2025-01-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField()),
                ('score', models.IntegerField()),
                ('subjectId', models.IntegerField()),
            ],
        ),
    ]
