# Generated by Django 5.1.4 on 2025-01-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quizattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
